version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Pre build"
  build:
    commands:
      - echo "Build started"
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo "Post build"
