version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Pre build"
      - src_account_id=$(echo $CODEBUILD_BUILD_ARN | cut -d':' -f5)
      - echo "Logging in to the pre_build Amazon ECR in ..."
      - $(aws ecr get-login --no-include-email --registry-ids ${src_account_id} --region "us-east-2")
  build:
    commands:
      - echo "Build started"
      - pip install -r requirements.txt
      - pytest tests
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t bo-demo-app .
      - docker tag bo-demo-app:latest 780182659516.dkr.ecr.us-east-2.amazonaws.com/bo-demo-app:latest
  post_build:
    commands:
      - echo "Post build"
      - docker push 780182659516.dkr.ecr.us-east-2.amazonaws.com/bo-demo-app:latest
