version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Pre build"
      - src_account_id=$(echo $CODEBUILD_BUILD_ARN | cut -d':' -f5)
      - echo "Logging in to the pre_build Amazon ECR in ..."
      - $(aws ecr get-login --no-include-email --registry-ids ${src_account_id} --region "us-east-2")
      - yum install -y awscli
      - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p ~/bin && cp ./aws-iam-authenticator ~/bin/aws-iam-authenticator && export PATH=~/bin:$PATH
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - "mkdir ~/.kube/"
      - "cp kube-config ~/.kube/config"
  build:
    commands:
      - echo "Build started"
      - pip install -r requirements.txt
      - pytest tests
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t bo-demo-app .
      - docker tag bo-demo-app:latest 780182659516.dkr.ecr.us-east-2.amazonaws.com/bo-demo-app:latest
  post_build:
    commands:
      - echo "Post build"
      - echo "Post build 2"
      - docker push 780182659516.dkr.ecr.us-east-2.amazonaws.com/bo-demo-app:latest
      - aws sts get-caller-identity
      - kubectl config view --minify
      - aws eks update-kubeconfig --name bo-demo-cluster-1 --region us-east-2
      - kubectl config view --minify
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY
      - aws configure set aws_secret_access_key $AWS_SECRET_KEY
      - aws configure set default.region us-east-2
      - aws iam get-user
      - kubectl get nodes
      - helm uninstall example
      - helm install example ./bo-demo-chart --set service.type=LoadBalancer